### ISSUE TITLE
今年PyCon China 2023的日程和讲师名单出来了吗？

### ISSUE THREAD

**Issue by tonyqus** [PyConChina/PyConChina2023#2]
我在[大会网站](https://cn.pycon.org/2023/)上没找到。

**Comment by greyli** [comment]
[活动行](https://www.huodongxing.com/event/2729331638800)上有目前确定的议程信息，后续最终日程会更新到网站上。

**Comment by frostming** [comment]
Closed by 851b0def0d5b29d73258dff7bd13718a0840ede7
